config/routes.rb
Rails.application.routes.draw do

  ############################
  # clearance
  ############################

  resources :passwords, controller: "clearance/passwords", only: [:create, :new]
  # resource :session, controller: "clearance/sessions", only: [:create]
  resource :session, controller: "sessions", only: [:create]
  resources :users, controller: "clearance/users", only: [:create] do
    resource :password,
      controller: "clearance/passwords",
      only: [:edit, :update]
  end

  get "/sign_in", to: "clearance/sessions#new", as: "sign_in"
  delete "/sign_out", to: "clearance/sessions#destroy", as: "sign_out"
  get "/sign_up", to: "clearance/users#new", as: "sign_up"

  ############################
  # admin
  ############################

  namespace :admin do
    concern :with_datatable do
      post 'datatable', on: :collection
    end

    resources :properties, concerns: [:with_datatable]

    root to: "properties#index"
  end

  ############################
  # normal
  ############################

  get 'dataTablesI18n/:lang', to: 'datatables#datatable_i18n'
  get 'addresses/find_by_zipcode/:zipcode', to: 'addresses#find_by_zipcode'

  root to: "home#index"
end

app/models/address.rb
class Address < ApplicationRecord
  has_one :property

  validates :address, :city, :neighborhood,  :state, :zipcode, presence: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/property.rb
class Property < ApplicationRecord
  belongs_to :property_type
  belongs_to :address

  has_and_belongs_to_many :rent_insurances

  accepts_nested_attributes_for :address
  accepts_nested_attributes_for :rent_insurances, allow_destroy: true

  enum category: { sell: 0, rent: 1 }

  delegate :name, to: :property_type, prefix: true

  validates :bathrooms, :category, :parking_space, :price,
            :reference, :rooms, :size, :title, presence: true
  validates :rent_insurances, presence: true, if: :property_to_rent?

  validates :reference, uniqueness: true

  monetize :price_cents
  validates_with CustomMoneyValidator # workaround numericality money gem bug

  def self.validate_filter_category(filter)
    category = filter.to_s.downcase.strip
    raise ArgumentError, 'Invalid filter' unless category_enum_valid?(category)
    true
  end

  def self.category_enum_valid?(enum)
    return false unless category_enum_value(enum).present?
    true
  end

  private

  def property_to_rent?
    rent?
  end

  def self.category_enum_value(value)
    defined_enums.deep_symbolize_keys.dig(:category, value.to_sym)
  end
end

app/models/property_type.rb
class PropertyType < ApplicationRecord
  has_many :properties

  validates :name, presence: true
end

app/models/rent_insurance.rb
class RentInsurance < ApplicationRecord
  has_and_belongs_to_many :properties

end

app/models/user.rb
class User < ApplicationRecord
  include Clearance::User
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController
  before_action :sanitize_zipcode

  def find_by_zipcode
    address = Address.find_by(zipcode: @zipcode)
    address = Correios::CEP::AddressFinder.get(@zipcode) if address.nil?

    respond_to do |format|
      format.js { render json: address.to_json }
    end
  end

  private

  def sanitize_zipcode
    @zipcode = permitted_params[:zipcode].strip.tr('-', '')
  end

  def permitted_params
    params.permit(:zipcode)
  end
end

app/controllers/admin/application_controller.rb
module Admin
  class ApplicationController < ActionController::Base
    include Clearance::Controller

    before_action :require_login
  end
end

app/controllers/admin/properties_controller.rb
module Admin
  class PropertiesController < ApplicationController
    include InputHelper

    before_action :set_filter_category, only: [:index, :datatable]
    before_action :set_property, only: [:show, :edit, :update, :destroy]
    before_action :sanitize_price,  only: [:create, :update]

    def index
      presenter_params = {
        filter_category: @filter_category
      }
      @indexPresenter = PropertyIndexPresenter.new(presenter_params)
    end

    def show
      @property = @property.decorate
    end

    def new
      @property = Property.new
      @property.build_address
    end

    def edit
      @property.build_address if @property.address.nil?
    end

    def create
      @property = Property.new(property_params)

      respond_to do |format|
        if @property.save
          format.html do
            flash[:success] = I18n.t('actions.created', model: I18n.t('activerecord.models.property.one'))
            redirect_to admin_property_path(@property)
          end
        else
          format.html { render :new }
        end
      end
    end

    def update
      respond_to do |format|
        if @property.update(property_params)
          format.html do
            flash[:success] = I18n.t('actions.updated', model: I18n.t('activerecord.models.property.one'))
            redirect_to admin_property_path(@property)
          end
        else
          format.html { render :edit }
        end
      end
    end

    def destroy
      @property.destroy
      respond_to do |format|
        format.js do
          flash.now[:success] = I18n.t('actions.deleted', model: I18n.t('activerecord.models.property.one'))
          render layout: false, content_type: 'text/javascript'
        end
      end
    end

    def datatable
      datatable_params = {
        filter_category: @filter_category
      }
      render json: PropertyDatatable.new(params, datatable_params)
    end

    private

    def set_filter_category
      filter = permitted_params[:filter]
      return if filter.nil?

      Property.validate_filter_category(filter)

      @filter_category = filter
    end

    def set_property
      @property = Property.find(permitted_params[:id])
    end

    def sanitize_price
      property_params[:price] = strip_input_mask(property_params[:price])
    end

    def permitted_params
      params.permit(:filter, :id)
    end

    def property_params
      params.require(:property).permit(
        :bathrooms, :category, :description, :furniture, :parking_space,
        :pet_friendly, :property_type_id, :price, :reference, :rooms,
        :show_address, :size, :title,
        address_attributes: [
          :address, :city, :complement, :id, :neighborhood, :state, :zipcode
        ],
        rent_insurance_ids: []
      )
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/datatables_controller.rb
class DatatablesController < ActionController::Base
  before_action :load_i18n_file, only: [:datatable_i18n]

  def datatable_i18n
    render json: @i18n_data
  end

  private

  def load_i18n_file
    file_path = Rails.root.join('config', 'locales', 'datatables', "#{permitted_params[:lang]}.json")
    file = File.open file_path
    @i18n_data = JSON.load file
    file.close
  end

  def permitted_params
    params.permit(:lang)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    redirect_to admin_properties_path
  end
end

app/controllers/sessions_controller.rb
class SessionsController < Clearance::SessionsController
  def create
    @user = authenticate(params)

    sign_in(@user) do |status|
      if status.success?
        flash[:success] = I18n.t('flashes.success_login', username: current_user.username)
        redirect_back_or url_after_create
      else
        flash.now[:error] = status.failure_message
        render template: "sessions/new", status: :unauthorized
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def noty_flash_message
    javascript_tag do
      flash.map do |message_type, message|
        "new Noty({
          theme: 'bootstrap-v4',
          text: '#{message}',
          type: '#{message_type}',
          layout: 'topCenter',
          animation: {
            open: 'animated fadeInDown',
            close: 'animated fadeOutUp'
          },
          timeout: 3000,
          visibilityControl: true
        }).show();"
      end.join("\n").html_safe
    end
  end
end

app/helpers/input_helper.rb
module InputHelper
  def strip_input_mask(amount)
    amount = amount.tr('R$', '').tr('.', '').tr(',', '.').strip
  end
end

app/views/admin/addresses/_nested_form.html.erb
<%
  content_for :javascript do
    javascript_include_tag 'forms/address_form.js'
  end
%>

<%= f.input :zipcode, input_html: { class: 'zipcode zipcode-mask' }, placeholder: t('simple_form.placeholders.address.zipcode') %>
<%= f.input :address, placeholder: t('simple_form.placeholders.address.address') %>
<%= f.input :complement, placeholder: t('simple_form.placeholders.address.complement') %>
<%= f.input :neighborhood, placeholder: t('simple_form.placeholders.address.neighborhood') %>
<%= f.input :state, input_html: { class: 'state-mask' }, placeholder: t('simple_form.placeholders.address.state') %>
<%= f.input :city, placeholder: t('simple_form.placeholders.address.city') %>

app/views/admin/addresses/_show.html.erb
<p>
  <strong><%= t('activerecord.attributes.address.zipcode') %>:</strong>
  <%= address.zipcode %>
</p>
<p>
  <strong><%= t('activerecord.attributes.address.address') %>:</strong>
  <%= address.address %>
</p>
<p>
  <strong><%= t('activerecord.attributes.address.complement') %>:</strong>
  <%= address.complement %>
</p>
<p>
  <strong><%= t('activerecord.attributes.address.neighborhood') %>:</strong>
  <%= address.neighborhood %>
</p>
<p>
  <strong><%= t('activerecord.attributes.address.state') %>:</strong>
  <%= address.state %>
</p>

<p>
  <strong><%= t('activerecord.attributes.address.city') %>:</strong>
  <%= address.city %>
</p>

app/views/admin/properties/_form.html.erb
<%
  content_for :javascript do
    javascript_include_tag 'forms/forms.js'
  end
%>

<%= simple_form_for([:admin, property],
        wrapper: :floating_labels_form,
        wrapper_mappings: { select: :floating_labels_select }) do |f| %>

  <%= f.error_notification %>

  <%= f.input :category, collection: PropertyDecorator::CATEGORY_MAPPING, label_method: :last, value_method: :first, include_blank: false %>

  <%= f.association :rent_insurances, as: :check_boxes %>

  <%= f.association :property_type, include_blank: false %>

  <%= f.input :reference, placeholder: t('simple_form.placeholders.property.reference') %>
  <%= f.input :title, placeholder: t('simple_form.placeholders.property.title') %>

  <%= f.simple_fields_for(:address,
        wrapper: :floating_labels_form,
        wrapper_mappings: { select: :floating_labels_select }) do |fa| %>

    <%= render 'admin/addresses/nested_form', f: fa %>
  <% end%>
  <%= f.input :show_address, wrapper: :custom_boolean_switch  %>

  <%= f.input :price, input_html: { class: 'currency-mask' }, placeholder: t('simple_form.placeholders.property.price') %>
  <%= f.input :size, placeholder: t('simple_form.placeholders.property.size') %>
  <%= f.input :rooms, placeholder: t('simple_form.placeholders.property.rooms') %>
  <%= f.input :bathrooms, placeholder: t('simple_form.placeholders.property.bathrooms') %>
  <%= f.input :parking_space, placeholder: t('simple_form.placeholders.property.parking_space') %>

  <%= f.input :furniture, wrapper: :custom_boolean_switch %>
  <%= f.input :pet_friendly, wrapper: :custom_boolean_switch  %>

  <%= f.input :description, placeholder: t('simple_form.placeholders.property.description') %>

  <div class="d-sm-flex justify-content-end mb-4">
    <%= f.button :submit, class: "btn-primary" %>
  </div>
<% end %>

app/views/admin/properties/destroy.js.erb
$('.action-delete').bind('ajax:success', function(){
  $('#dataTable').DataTable()
    .row(
      $("tr#<%= @property.id %>")
    )
    .remove()
    .draw( false );

  $('#flash-container').html("<%= j render 'shared/flash' %>");
});

app/views/admin/properties/edit.html.erb
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800"><%= t('property.edit.title') %></h1>
  <a
    href="<%= admin_properties_path %>"
    class="d-none d-sm-inline-block btn btn-primary shadow-sm"
  >
    <i class="fas fa-arrow-circle-left fa-sm text-white-50"></i>
    <%= t('actions.back') %>
  </a>
</div>

<%= render 'form', property: @property %>

app/views/admin/properties/index.html.erb
<%
  content_for :stylesheet do
    stylesheet_link_tag 'dataTables.bootstrap4.min', media: 'all', 'data-turbolinks-track': 'reload'
  end
%>

<%
  content_for :javascript do
    javascript_include_tag 'datatables.js'
  end
%>

<div class="d-sm-flex align-items-center justify-content-between">
  <div class="d-sm-flex flex-column align-items-left justify-content-between">
    <h1 class="h3 mb-0 text-gray-800"><%= t('property.index.title') %></h1>
    <%= @indexPresenter.subtitle %>
  </div>

  <a
    href="<%= new_admin_property_path %>"
    class="d-none d-sm-inline-block btn btn-primary shadow-sm"
  >
    <i class="fas fa-plus-circle fa-sm text-white-50"></i>
    <%= t('actions.new') %>
  </a>
</div>

<div class="card shadow mb-4">
  <div class="card-body">
    <div class="table-responsive">
      <table
        class="table table-bordered"
        id="dataTable"
        data-source="<%= @indexPresenter.datatable_source %>"
        width="100%"
        cellspacing="0"
      >
        <thead>
          <tr>
            <th><%= t('activerecord.attributes.property.reference') %></th>
            <th><%= t('property.index.table.property_type') %></th>
            <th><%= t('activerecord.attributes.property.price') %></th>
            <th></th>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <th><%= t('activerecord.attributes.property.reference') %></th>
            <th><%= t('property.index.table.property_type') %></th>
            <th><%= t('activerecord.attributes.property.price') %></th>
            <th></th>
          </tr>
        </tfoot>
        <tbody></tbody>
      </table>
    </div>
  </div>
</div>

app/views/admin/properties/new.html.erb
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800"><%= t('property.create.title') %></h1>
  <a
    href="<%= admin_properties_path %>"
    class="d-none d-sm-inline-block btn btn-primary shadow-sm"
  >
    <i class="fas fa-arrow-circle-left fa-sm text-white-50"></i>
    <%= t('actions.back') %>
  </a>
</div>

<%= render 'form', property: @property %>

app/views/admin/properties/show.html.erb
<div class="d-sm-flex align-items-center justify-content-between mb-4">
  <h1 class="h3 mb-0 text-gray-800"><%= t('property.show.title') %></h1>

  <div class="d-sm-flex align-items-center justify-content-between">
    <a
      href="<%= edit_admin_property_path(@property) %>"
      class="d-none d-sm-inline-block btn btn-primary shadow-sm mr-2"
    >
      <i class="fas fa-edit fa-sm text-white-50"></i>
      <%= t('actions.edit') %>
    </a>

    <a
      href="<%= admin_properties_path %>"
      class="d-none d-sm-inline-block btn btn-primary shadow-sm"
    >
      <i class="fas fa-arrow-circle-left fa-sm text-white-50"></i>
      <%= t('actions.back') %>
    </a>
  </div>
</div>

<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('activerecord.attributes.property.category') %>:</strong>
  <%= @property.mapped_category %>
</p>

<% if @property.rent? %>
  <p>
    <strong><%= t('activerecord.attributes.property.rent_insurances') %>:</strong>
    <%= @property.rent_insurances.map(&:name).join(', ') %>
  </p>
<% end %>

<p>
  <strong><%= t('activerecord.attributes.property.property_type') %>:</strong>
  <%= @property.property_type_name %>
</p>
<p>
  <strong><%= t('activerecord.attributes.property.reference') %>:</strong>
  <%= @property.reference %>
</p>
<p>
  <strong><%= t('activerecord.attributes.property.title') %>:</strong>
  <%= @property.title %>
</p>

<%= render 'admin/addresses/show', address: @property.address %>
<p>
  <strong><%= t('activerecord.attributes.property.show_address') %>:</strong>
  <%= I18n.t("boolean.#{@property.show_address}") %>
</p>

<p>
  <strong><%= t('activerecord.attributes.property.price') %>:</strong>
  <%= @property.price.format %>
</p>
<p>
  <strong><%= t('activerecord.attributes.property.size') %>:</strong>
  <%= @property.size %>
</p>
<p>
  <strong><%= t('activerecord.attributes.property.rooms') %>:</strong>
  <%= @property.rooms %>
</p>
<p>
  <strong><%= t('activerecord.attributes.property.bathrooms') %>:</strong>
  <%= @property.bathrooms %>
</p>
<p>
  <strong><%= t('activerecord.attributes.property.parking_space') %>:</strong>
  <%= @property.parking_space %>
</p>
<p>
  <strong><%= t('activerecord.attributes.property.furniture') %>:</strong>
  <%= I18n.t("boolean.#{@property.furniture}") %>
</p>
<p>
  <strong><%= t('activerecord.attributes.property.pet_friendly') %>:</strong>
  <%= I18n.t("boolean.#{@property.pet_friendly}") %>
</p>
<p>
  <strong><%= t('activerecord.attributes.property.description') %>:</strong>
  <%= @property.description %>
</p>

app/views/layouts/admin/_sidebar.html.erb
<!-- Sidebar -->
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

  <!-- Sidebar - Brand -->
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="<%= admin_properties_path %>">
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-laugh-wink"></i>
    </div>
    <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
  </a>

  <!-- Divider -->
  <hr class="sidebar-divider my-0">

  <!-- Nav Item - Dashboard -->
  <li class="nav-item active">
    <a class="nav-link" href="<%= admin_properties_path %>">
      <i class="fa fa-fw fa-tachometer-alt"></i>
      <span>Dashboard</span></a>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider">

  <!-- Nav Item - Pages Collapse Menu -->
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
      <i class="fas fa-fw fa-home"></i>
      <span>Imóveis</span>
    </a>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <a class="collapse-item" href="<%= admin_properties_path %>">Todos</a>
        <a class="collapse-item" href="<%= admin_properties_path(filter: 'rent') %>">Locação</a>
        <a class="collapse-item" href="<%= admin_properties_path(filter: 'sell') %>">Venda</a>
      </div>
    </div>
  </li>

  <!-- Divider -->
  <hr class="sidebar-divider d-none d-md-block">

  <!-- Sidebar Toggler (Sidebar) -->
  <div class="text-center d-none d-md-inline">
    <button class="rounded-circle border-0" id="sidebarToggle"></button>
  </div>

</ul>
<!-- End of Sidebar -->

app/views/layouts/admin/_topbar.html.erb
 <!-- Topbar -->
 <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

  <!-- Sidebar Toggle (Topbar) -->
  <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
  </button>

  <!-- Topbar Search -->
  <%# <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
    <div class="input-group">
      <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
      <div class="input-group-append">
        <button class="btn btn-primary" type="button">
          <i class="fas fa-search fa-sm"></i>
        </button>
      </div>
    </div>
  </form> %>

  <!-- Topbar Navbar -->
  <ul class="navbar-nav ml-auto">

    <!-- Nav Item - Search Dropdown (Visible Only XS) -->
    <li class="nav-item dropdown no-arrow d-sm-none">
      <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-search fa-fw"></i>
      </a>
      <!-- Dropdown - Messages -->
      <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in" aria-labelledby="searchDropdown">
        <form class="form-inline mr-auto w-100 navbar-search">
          <div class="input-group">
            <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
            <div class="input-group-append">
              <button class="btn btn-primary" type="button">
                <i class="fas fa-search fa-sm"></i>
              </button>
            </div>
          </div>
        </form>
      </div>
    </li>

    <!-- Nav Item - Alerts -->
    <li class="nav-item dropdown no-arrow mx-1">
      <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-bell fa-fw"></i>
        <!-- Counter - Alerts -->
        <span class="badge badge-danger badge-counter">3+</span>
      </a>
      <!-- Dropdown - Alerts -->
      <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="alertsDropdown">
        <h6 class="dropdown-header">
          Alerts Center
        </h6>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="mr-3">
            <div class="icon-circle bg-primary">
              <i class="fas fa-file-alt text-white"></i>
            </div>
          </div>
          <div>
            <div class="small text-gray-500">December 12, 2019</div>
            <span class="font-weight-bold">A new monthly report is ready to download!</span>
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="mr-3">
            <div class="icon-circle bg-success">
              <i class="fas fa-donate text-white"></i>
            </div>
          </div>
          <div>
            <div class="small text-gray-500">December 7, 2019</div>
            $290.29 has been deposited into your account!
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="mr-3">
            <div class="icon-circle bg-warning">
              <i class="fas fa-exclamation-triangle text-white"></i>
            </div>
          </div>
          <div>
            <div class="small text-gray-500">December 2, 2019</div>
            Spending Alert: We've noticed unusually high spending for your account.
          </div>
        </a>
        <a class="dropdown-item text-center small text-gray-500" href="#">Show All Alerts</a>
      </div>
    </li>

    <!-- Nav Item - Messages -->
    <li class="nav-item dropdown no-arrow mx-1">
      <a class="nav-link dropdown-toggle" href="#" id="messagesDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <i class="fas fa-envelope fa-fw"></i>
        <!-- Counter - Messages -->
        <span class="badge badge-danger badge-counter">7</span>
      </a>
      <!-- Dropdown - Messages -->
      <div class="dropdown-list dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="messagesDropdown">
        <h6 class="dropdown-header">
          Message Center
        </h6>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="dropdown-list-image mr-3">
            <img class="rounded-circle" src="https://source.unsplash.com/fn_BT9fwg_E/60x60" alt="">
            <div class="status-indicator bg-success"></div>
          </div>
          <div class="font-weight-bold">
            <div class="text-truncate">Hi there! I am wondering if you can help me with a problem I've been having.</div>
            <div class="small text-gray-500">Emily Fowler · 58m</div>
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="dropdown-list-image mr-3">
            <img class="rounded-circle" src="https://source.unsplash.com/AU4VPcFN4LE/60x60" alt="">
            <div class="status-indicator"></div>
          </div>
          <div>
            <div class="text-truncate">I have the photos that you ordered last month, how would you like them sent to you?</div>
            <div class="small text-gray-500">Jae Chun · 1d</div>
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="dropdown-list-image mr-3">
            <img class="rounded-circle" src="https://source.unsplash.com/CS2uCrpNzJY/60x60" alt="">
            <div class="status-indicator bg-warning"></div>
          </div>
          <div>
            <div class="text-truncate">Last month's report looks great, I am very happy with the progress so far, keep up the good work!</div>
            <div class="small text-gray-500">Morgan Alvarez · 2d</div>
          </div>
        </a>
        <a class="dropdown-item d-flex align-items-center" href="#">
          <div class="dropdown-list-image mr-3">
            <img class="rounded-circle" src="https://source.unsplash.com/Mv9hjnEUHR4/60x60" alt="">
            <div class="status-indicator bg-success"></div>
          </div>
          <div>
            <div class="text-truncate">Am I a good boy? The reason I ask is because someone told me that people say this to all dogs, even if they aren't good...</div>
            <div class="small text-gray-500">Chicken the Dog · 2w</div>
          </div>
        </a>
        <a class="dropdown-item text-center small text-gray-500" href="#">Read More Messages</a>
      </div>
    </li>

    <div class="topbar-divider d-none d-sm-block"></div>

    <!-- Nav Item - User Information -->
    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%= current_user.username.downcase.capitalize %></span>
        <i class="fas fa-user-circle fa-2x"></i>
      </a>
      <!-- Dropdown - User Information -->
      <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
        <%# <a class="dropdown-item" href="#">
          <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
          Profile
        </a>
        <a class="dropdown-item" href="#">
          <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
          Settings
        </a>
        <a class="dropdown-item" href="#">
          <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
          Activity Log
        </a> %>
        <%# <div class="dropdown-divider"></div> %>
        <a class="dropdown-item" href="<%= sign_out_path %>" data-method="delete" data-toggle="modal" data-target="#logoutModal">
          <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
          <%= t('layouts.application.sign_out') %>
        </a>
      </div>
    </li>

  </ul>

</nav>
<!-- End of Topbar -->

app/views/shared/_flash.html.erb
<%= noty_flash_message %>

app/views/users/_form.html.erb
<div class="text-field">
  <%= form.label :email %>
  <%= form.text_field :email, type: 'email' %>
</div>

<div class="password-field">
  <%= form.label :password %>
  <%= form.password_field :password %>
</div>

app/views/users/new.html.erb
<div id="clearance" class="sign-up">
  <h2><%= t(".title") %></h2>

  <%= form_for @user do |form| %>
    <%= render partial: '/users/form', object: form %>

    <div class="submit-field">
      <%= form.submit %>
    </div>

    <div class="other-links">
      <%= link_to t(".sign_in"), sign_in_path %>
    </div>
  <% end %>
</div>